In [1]:
import numpy as np

### Creating Arrays

1. np.array([])
2. np.arange()
3. np.linspace()
4. np.zeros()
5. np.ones()
6. np.random.rand()
7. np.random.randint()
8. np.random.randn()

In [2]:
a = np.array([])

In [3]:
print(a)

[]


In [4]:
a

array([], dtype=float64)

In [5]:
len(a)

0

In [6]:
sum(a)

0

In [7]:
a.shape

(0,)

In [8]:
a.size

0

In [9]:
a.dtype # detecting the datatype

dtype('float64')

In [10]:
a.astype('int8') # changing the data type

array([], dtype=int8)

In [11]:
a.dtype

dtype('float64')

In [12]:
a.tolist()

[]

In [13]:
type(a)

numpy.ndarray

In [14]:
type(a.tolist())

list

In [15]:
b = np.array([3,4,5,6,7,8])
b

array([3, 4, 5, 6, 7, 8])

In [16]:
b.shape

(6,)

In [17]:
b.size

6

In [18]:
b.dtype

dtype('int32')

In [33]:
c = np.array([[4,5,6,8],[9,3,76,2],[56,76,3,8]])
c

array([[ 4,  5,  6,  8],
       [ 9,  3, 76,  2],
       [56, 76,  3,  8]])

In [31]:
c.shape

(3, 4)

In [32]:
c.size

12

#### data operation

In [20]:
# 1. Accessing Data
# Indexing -> arr[ind] (slicing is available here)
# Subscripting -> arr[row,col,3rd,4th,........nd] (slicing is available here)

In [21]:
b[3]

6

In [22]:
b[:3]

array([3, 4, 5])

In [34]:
c[:2,1:]

array([[ 5,  6,  8],
       [ 3, 76,  2]])

In [35]:
b

array([3, 4, 5, 6, 7, 8])

In [36]:
b[3] = 16

In [37]:
b

array([ 3,  4,  5, 16,  7,  8])

In [38]:
b*3

array([ 9, 12, 15, 48, 21, 24])

In [39]:
c+10

array([[14, 15, 16, 18],
       [19, 13, 86, 12],
       [66, 86, 13, 18]])

In [41]:
c

array([[ 4,  5,  6,  8],
       [ 9,  3, 76,  2],
       [56, 76,  3,  8]])

In [40]:
c.reshape(2,6)

array([[ 4,  5,  6,  8,  9,  3],
       [76,  2, 56, 76,  3,  8]])

In [43]:
c.T # Transpose of matrix

array([[ 4,  9, 56],
       [ 5,  3, 76],
       [ 6, 76,  3],
       [ 8,  2,  8]])

In [48]:
# c[4,0:4] = [9,99,999,199]

In [54]:
np.append(c, [[9,99,999,199]])

array([  4,   5,   6,   8,   9,   3,  76,   2,  56,  76,   3,   8,   9,
        99, 999, 199])

In [ ]:
np.insert()

In [56]:
d = np.append(c, [[9,99,999,199]],axis=0)
d

array([[  4,   5,   6,   8],
       [  9,   3,  76,   2],
       [ 56,  76,   3,   8],
       [  9,  99, 999, 199]])

In [59]:
np.append(d,[[11],[411],[311],[121]],axis=1)

array([[  4,   5,   6,   8,  11],
       [  9,   3,  76,   2, 411],
       [ 56,  76,   3,   8, 311],
       [  9,  99, 999, 199, 121]])

#### statistical operation

In [55]:
c

array([[ 4,  5,  6,  8],
       [ 9,  3, 76,  2],
       [56, 76,  3,  8]])

In [60]:
c.sum()

256

In [61]:
c.sum(axis=1)

array([ 23,  90, 143])

In [62]:
c.sum(axis=0)

array([69, 84, 85, 18])

#### mathematics